### ISSUE TITLE
semver-tag prerelease input is optional but breaks if omitted

### ISSUE THREAD

**Issue by ntse** [ministryofjustice/opg-github-actions#48]
The `prerelease` input on semver-tag is optional but if it's left out then a blank string is passed to main.go which causes the below error:

`time=2024-03-14T10:38:59.695Z level=ERROR source=/home/runner/work/opg-github-actions/opg-github-actions/go/main.go:151 msg="Argument [--prerelease] is required, but missing"
`

**Comment by charlesmmarshall** [comment]
PR releated to this error - https://github.com/ministryofjustice/opg-github-actions/pull/50
